# authority account: 0xf70193972ed189063e14cf18eeaf81dd23cab118 (password=thesis-poc)
# user account: 0x8f15e25fa5e2502a88000aa1dfb87e46150eae5f (password=user)
[parity]
chain = "chainspec.json"
base_path = "./node0"
[misc]
log_file = "./node0/node0.log"
[network]
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "parity_accounts"]
cors = ["all"]
[websockets]
port = 8450
apis = ["web3", "net", "eth", "pubsub", "personal", "signer", "parity", "parity_pubsub", "parity_accounts", "parity_set", "traces"]
origins = ["all"]
hosts = ["all"]
[account]
unlock = ["0x8f15e25fa5e2502a88000aa1dfb87e46150eae5f"]
password = ["node.pwds"]
[mining]
engine_signer = "0xf70193972ed189063e14cf18eeaf81dd23cab118"
reseal_on_txs = "none"
